import { nameToSlug } from "./utils.js";

/**
 * Static sub-section mapping per dofus.
 * Only dofus with meaningful geographic or thematic sub-sections are listed.
 * All other quests receive null sub_section by default.
 */
const RAW_OVERRIDES: Array<{
  dofusSlug: string;
  groups: Array<{ subSection: string; questNames: string[] }>;
}> = [
  {
    dofusSlug: "dofus-argente",
    groups: [
      {
        subSection: "Incarnam",
        questNames: [
          "L'anneau de tous les dangers",
          "Sous le regard des dieux",
          "Réponse a tout",
          "Le village dans les nuages",
          "Espoirs et tragedies",
          "Produits naturels",
          "Mort au rat",
          "Le metier des aventuriers",
          "La hache et la pioche",
          "Transport peu commun",
          "Boune un jour, boune toujours",
          "Preparation au combat",
          "Des vestiges de legende",
          "Mise a l'epreuve",
          "Champs de bataille",
          "Coups d'epee dans l'eau",
          "Vu du ciel",
          "Decime-moi des bouftous",
          "Un peu de pigment",
          "Chasse aux chapardams",
          "Lecon d'humilite",
          "La galette secrete",
          "Cryptologie",
          "Des chafers qui marchent",
          "Dans la gueule du milimulou",
          "Destination Astrub",
        ],
      },
      {
        subSection: "Astrub",
        questNames: [
          "Les principes d'archie m'aident",
          "Les deux font l'impair",
          "Les touffes des heros",
          "On marche sur des oeufs",
          "Conseil de classe",
          "Quete de classe",
          "Ca sent le gaz",
          "Balade en foret",
          "Ca tombe a l'eau",
          "Six pieds sous terre",
          "Tel est pris qui croyait prendre",
          "L'histoire en mouvement",
          "Biere qui roule n'amasse pas mousse",
          "Dejeuner a la fourchette",
          "Comme un pichon hors de l'eau",
          "La coupe des vices",
          "Le genie se meut",
          "Bucherons en detresse",
          "Qui seme le vent recolte l'artempeth",
          "Crise sanitaire",
          "La petite mission dans la prairie",
          "Livraison par interim",
          "Golemancien",
          "Le rebelle de la foret",
          "Restauration rapide",
          "De vrais rats de bibliotheque",
          "Chacha blues",
          "Les as de la cambriole",
          "Combat de rue",
          "Legende d'automne",
          "L'invasion des profanateurs de sepulture",
          "Le repos est dans le champs",
        ],
      },
    ],
  },
  {
    dofusSlug: "dofus-des-glaces",
    groups: [
      {
        subSection: "Frigost 1 et 2",
        questNames: [
          "En semant, se ment",
          "Pomdeupin vaut mieux que trois tu l'auras",
          "Massacre au hakapik",
          "Mettre son grain de sel",
          "Mauvaise graine",
          "Champ pomy",
          "Gant graine",
          "Les graines de la discorde",
          "Le champ des heros",
          "Champ borde le chateau",
          "Cent Vingt trois fleurs",
          "Fleuris mais rougissent",
          "La terre banquise",
          "La maire de glace",
          "Bienvenue a frigost",
          "Full contact",
          "Cent vingt trois fleurs, point comme les autres",
          "Les monologues du vaccin",
          "Antiroyaliste",
          "Bricole girl",
          "Star ski et dutch",
          "Epis d'Emi",
          "Hotel de glace",
          "La fonte des glaces",
          "Botanique-nique-nique",
          "Promenons-nous dans les bois",
          "A fleur de peau",
          "Peche en eaux gelees",
          "L'ombre et la glace",
          "Les joyeux de la couronne",
          "Les chasseurs",
          "La marche de l'imperatrice",
          "Lumiere sur l'ombre",
          "La peche a mel",
          "Mel odieuse",
          "Mel au drame",
          "Il est frais mon pichon",
          "L'essentiel est dans le lac gelé",
          "Frigost, une ile pas comme les autres",
          "Donjon et trouffions",
          "Il préfère la mort en mer",
          "Mes lys fleurs",
          "Fais dodo, t'auras du gâteau",
          "Chauffage a moindre frais",
          "Rose a lys, rose a lys, oh !",
          "A la recherche de dan lavy",
          "Fleuries mais rougissent",
          "Lavomatique",
          "A qui profite le boufmouth",
          "Heureux qui, comme les lys",
          "C'est frais, mais c'est pas grave",
          "Les rescapés de frigost",
          "Depot de ravitaillement",
          "Chaud du s.l.i.p.",
          "La rivalite",
          "Malediction",
          "Le nom de la mycose",
          "Sans ma barbe, quelle barbe",
          "Crocs n'en bourrent",
          "La-haut sur la montagne",
          "Un ami qui ne vous veut pas que du bien",
          "Ville fleurie",
          "Maya la belle",
          "Le pic qui glace",
          "Mission solution",
          "Developpement durable",
          "Les rescapes du village enseveli",
        ],
      },
      {
        subSection: "Frigost 3",
        questNames: [
          "Le tour de guet",
          "Rappel à la vie",
          "Moteur a explosion",
          "La fifille a son papa",
          "Mutinerie chez les armutins",
          "Guerre froide",
          "Au-dela du mur",
          "Les desseins de sylargh",
          "Vous avez demande la peau lisse ?",
          "La derniere carte",
          "La vie de chateau",
          "Chaud et froid",
          "Il faut mettre un terme aux maitres",
          "Crise d'ex-emma",
          "Les derniers rescapes",
          "La machine a demonter le temps",
          "Au fion du trou",
          "Le givre des revelations",
          "Un comte de faits divers",
          "Le dofus des glaces",
        ],
      },
    ],
  },
  {
    dofusSlug: "dofus-nebuleux",
    groups: [
      {
        subSection: "Enutrosor",
        questNames: [
          "Koffrologie",
          "Tresorphelinat",
          "Elle va finir par se faire coffrer",
          "Pompe a fric",
          "Les grandes galeries",
          "Malladie",
          "Espionnage industriel",
          "Prise d'otage",
          "La greve de la fin",
          "Malle des profondeurs",
          "La meilleure defense, c'est l'attaque",
          "Crache test",
          "Dephorrestation",
          "Phorreurs dans la brume",
          "La quatrieme dimension",
          "Le phormidiable au corps",
          "La pelle de la phorree",
          "Un coeur d'or",
          "Maudite generosite",
          "On ne prete qu'a richard",
          "Pour quelques kamas de plus",
          "Tout ce qui brille n'est pas or",
          "Un morceau de roi",
          "Coiffeur de genie",
          "Echantillonnage",
          "Touchez pas a grisebigle",
          "Prime de leche-majeste",
          "Reconnaissance de dettes",
          "Le silence est d'or",
          "Laisse en plan",
          "Parler au Dieu Enutrof",
        ],
      },
      {
        subSection: "Srambad",
        questNames: [
          "La seinoise",
          "Ca katche ou ca casse",
          "Faux-semblants",
          "Ca se katche",
          "Un ring pour les gouverner tous",
          "Fanfouille",
          "Les troupiers",
          "Viande fraiche",
          "Necrotiques, tiques, tiques",
          "Epidemiologie",
          "La peche au poison",
          "Comme un poison dans l'eau",
          "Tique attaque",
          "Sa majeste des necrotiques",
          "L'art me ment",
          "La morte adele",
          "Les sentiers de la perdition",
          "Le bazar du bizarre",
          "Un chafer dans le placard",
          "Bouchees a la reine",
          "La cour des miracles",
          "Os sitot dit, aussitot fait",
          "Balance la sauce",
          "Memoires d'outre-tombe",
          "Courir apres des ombres",
          "Sortir de l'ombre",
          "La chapelle noire",
          "Presume coupable",
          "Depuis l'enfer",
          "La grosse commission",
          "Aller voir le Dieu Sram",
        ],
      },
      {
        subSection: "Xelorium",
        questNames: [
          "C'est ton destin",
          "Retour vers le present",
          "Anomalies temporelles",
          "Prisonniers du temps",
          "Les demons de midi",
          "Aux origines du mal",
          "C'est quoi ton 06",
          "Terminutor le jugement de la machine",
          "De fil en aiguille",
          "La vie l'hormonde et le reste",
          "Failles spatio-temporelles",
          "Les voleurs de couleurs",
          "Juste une illusion",
          "Maboul de cristal",
          "L'armee des 12 dingues",
          "Demain ne meurt jamais",
          "Les visiteurs du futur",
          "Aujourd'hui a jamais",
          "Tout ce qu'il te faut c'est tuer",
          "La verite est au fond du puits",
          "Les sables du temps",
          "Dechirures temporelles",
          "Futur anterieur",
          "Guerre temporelle",
          "L'etendue godelique",
          "Aller voir le Dieu Xelor",
          "La quete de l'oiseau du temps",
        ],
      },
    ],
  },
  {
    dofusSlug: "dofus-ivoire",
    groups: [
      {
        subSection: "Prérequis - Partie 1",
        questNames: [
          "Entrainement avec Tarche",
          "La serveuse Dame Cloude",
          "Du pain pour les braves",
          "Ned le dentiste",
          "Entrainement avec Torche",
          "Cartes spéciales d'Amayiro",
          "A vol d'oiseau",
          "Pas de fainéants dans les rangs",
          "Premiere visite a Brakmar",
          "Un sanglier un peu trop agressif",
          "Du repos mais pas trop",
          "Recouvrement de dette à la Tabasse",
          "Pot l'agent double",
          "De la poudre aux yeux de Brâkmar",
          "Une breche à Bonta",
          "D'egouts temps",
          "L'elite squelettique",
          "La foire du Trool suspectee",
          "Le Tabi d'Amayiro",
          "Le fantôme de Tsog",
          "Des anneaux sur le bout des doigts",
          "La fureur du Holbaid",
          "Des capes Bontariennes",
          "Corvee de patate",
          "Lyeno, Abraknyde malgre lui",
          "Au service de Danathor",
          "Amayiro à l'ombre du Champo",
          "Le deces de Rimaraf",
          "Poison de scorbute pour la prison",
          "Dike Tarak, la menace",
          "Des combats pas tres legaux",
          "Mission de reconnaissance au cimetiere",
          "Vengeance par procuration",
          "La lettre anonyme",
          "Tabi t'a fleuri",
          "Des badges pour la bonne cause",
          "Lecon de cuisine",
          "Ras le bol de Lenglad",
          "Dapyus n'est pas doue",
          "C'est stupefiant",
          "Vin diou",
          "Les Ecas ne flippent pas",
          "Plaine de chats",
          "A l'endroit, à l'envers",
          "Dans la gueule du chacha",
          "Alimentaire mon cher",
          "Bouc a misere",
          "Flagrant delire",
          "Quand y'en a marre de brakmar",
          "La capture",
          "Le port salue",
          "L'equipe ment",
          "Une partie de cache-cache",
          "Pour vivre heureux",
          "La tactique des gens d'armes",
          "La panoplie du milicien",
          "Ambition ambigue",
          "Traknar",
          "La Grafioze",
          "Attaque a retardement",
          "Une rumeur interessante",
          "Investigations a moon",
          "Maniere douce",
          "Histoires de tortues",
          "Bandanarthrie",
          "Course-poursuite",
          "A la poursuite d'octolliard rouge",
          "Une corne edfrit sans sel",
          "Un sombre pouvoir",
          "Le subterfuge de la corne",
          "Un coupable ideal",
          "Un peu de juge hot",
          "De drôles de témoins",
          "Sram d'egoutant",
          "Si j'avais un marteau",
          "Esprit, es-tu la",
          "Vol du Temps",
          "La memoire en lambeaux",
          "Pense-bete",
          "L'eclat de l'aube",
          "Ingerence en amakna",
          "Petites faveurs entre amis",
          "Les gardiens de la galerie",
          "Le plateau de leng",
          "Gele à pierre fendre",
          "L'ascension de qu'tan",
          "Il ne faut pas se fier aux apparences",
          "On se calme",
          "Tout est bien qui finit mal",
          "Ca fait froid dans le dos",
          "Cambriolage a duree determinee",
          "C'est toujours dur le matin",
          "Je panse donc j'essuie",
          "L'aube des morts-vivants",
          "Un chemin tout trace",
          "Enigma",
          "A glacer le sang",
          "A l'ombre des murs",
          "Fee d'hiver",
          "L'exorciste",
          // — Brakmar (100 quêtes + 2 bis) —
          "Cliquetis fou",
          "Le professionnel",
          "Un coup de fouet",
          "Le dentiste dement",
          "La revanche de mak",
          "La noirceur des armes blanches",
          "La mise à mort",
          "Les gardes d'honneur... a punir",
          "Un oubli regrettable",
          "Tete de gland",
          "Pauvre larve",
          "Pauvre larve... doree",
          "Agent double et demi",
          "Livreur de mauvaise nouvelle",
          "Une collection digne de Xilebo",
          "D'egout pille",
          "Le tabi mangeur de blops",
          "Alchimie malfaisante",
          "Des capes typiques",
          "Le testament du papa",
          "Amadouer ou corrompre",
          "Taxe gratuite",
          "Par la force ou par la finesse",
          "Le dur travail d'eplucheur de patates",
          "Cruel, mais à quel point",
          "Activites volcaniques",
          "Chasse a l'espion",
          "Un petit oubli",
          "Du venin sinon rien",
          "Le defi du maitre guerrier",
          "Joie de courte duree",
          "Au combat",
          "Un assassin... a Bonta",
          "Un dentier pour l'ami mak",
          "Un choix difficile",
          "Arrivee a bon port",
          "Humiliation sans precedent",
          "Opposition aux opposants",
          "A la rescousse d'un incapable",
          "Mulanthropie",
          "Triple x",
          "X comme xephires",
          "Operation commando",
          "Rencontre du premier type",
          "Joyau... ze fete",
          "Le cristal de kain dharyn",
          "Cambriolage",
          "Livraison rapide",
          "Le moment de vérité",
          "Le puits sans fond",
          "Le carnage des plaines",
          "Dans la peau de sphincter cell",
          "Le forgeron aux deux mains gauches",
          "Mon nom est poison",
          "Un maitre es pion",
          "Le magnanime",
          "Supermilicien",
          "Le forgeron",
          "Paranoia aigue",
          "A la maniere des Brakmariens",
          "Le tresor de La descemer",
          "Une rumeur allechante",
          "Enquete a moon",
          "Maniere forte",
          "Retour aux origines",
          "Une faille dans sa carapace",
          "Les documents avant tout",
          "Les ordres sont-ils les ordres",
          "Contre-espion",
          "Histoires de salaces",
          "Affrontement",
          "Legitime defense",
          "L'epee maudite",
          "Allez, ce fer",
          "Poignee d'amour",
          "Le marteau des chus",
          "L'epee, ca sent mauvais",
          "Plus, plus de puissance",
          "Des recherches sur la corne",
          "Maitre chanteur",
          "Comploteur malgre lui",
          "Le roi estitsh",
          "Le trou d'uk",
          "Gaspiller l'energie ensemble",
          "Gemme les joyaux",
          "L'arakne de leng",
          "Marque d'une pierre blanche",
          "L'essor de qu'tan",
          "L'habit ne fait pas le moine",
          "Les clefs du malheur",
          "Chaud devant",
          "La vengeance est un plat qui se mange froid",
          "Melodie en sous-sol",
          "Un monde en pets",
          "Mieux vaut guerir que mourir",
          "Le crepuscule des morts-vivants",
          "Le faux cul",
          "Cryptomane",
          "Sueurs froides",
          "Sur la route d'erazal",
          "Lettre à ilyz",
          "La danse macabre",
          // — Ordres Bonta —
          "Apprentissage : Disciple de menalt",
          "Apprentissage : Ecuyer",
          "Apprentissage : Chevalier de l'espoir",
          "Apprentissage : Champion merveilleux",
          "Apprentissage : Heros legendaire",
          "Apprentissage : Disciple de silvosse",
          "Apprentissage : Espion silencieux",
          "Apprentissage : Chasseur de renegats",
          "Apprentissage : Assassin supreme",
          "Apprentissage : Maitre des illusions",
          "Apprentissage : Disciple de jiva",
          "Apprentissage : Apprenti eclaire",
          "Apprentissage : Adepte des ecrits",
          "Apprentissage : Maitre des parchemins",
          "Apprentissage : Gardien du savoir",
          // — Ordres Brakmar —
          "Apprentissage : Disciple de djaul",
          "Apprentissage : Surineur",
          "Apprentissage : Chevalier du desespoir",
          "Apprentissage : Champion du chaos",
          "Apprentissage : Heros de l'apocalypse",
          "Apprentissage : Disciple de brumaire",
          "Apprentissage : Espion sombre",
          "Apprentissage : Chasseur d'ames",
          "Apprentissage : Psychopathe",
          "Apprentissage : Maitre des ombres",
          "Apprentissage : Disciple d'hecate",
          "Apprentissage : Apprenti sombre",
          "Apprentissage : Adepte des Douleurs",
          "Apprentissage : Maitre des sevices",
          "Apprentissage : Gardien des tortures",
        ],
      },
      {
        subSection: "Prérequis - Partie 2",
        questNames: [
          "Les touffes des heros",
          "L'anneau de tous les dangers",
          "Sous le regard des dieux",
          "Réponse a tout",
          "Le village dans les nuages",
          "Espoirs et tragedies",
          "Dans la gueule du milimulou",
          "Destination Astrub",
          "Les principes d'archie m'aident",
          "On marche sur des oeufs",
          "Conseil de classe",
          "Quete de classe",
          "Ca sent le gaz",
          "Balade en foret",
          "Le reveil de pandala",
          "Le receptacle des dofus",
          "Intrusion chez les wabbits",
          "Un sage parmi les sages",
          "Protection divine",
          "Un pendule pour guider ses pas",
          "Voir le dark vlad et mourir... ou pas",
          "La magicienne des marecages",
          "Koffrologie",
          "Tresorphelinat",
          "Malladie",
          "Les grandes galeries",
          "Espionnage industriel",
          "La terre banquise",
          "La maire de glace",
          "Bienvenue a frigost",
          "L'essentiel est dans le lac gelé",
          "La bete interieure",
          "Allumer le feu",
          "La garde meurt mais ne se rend pas",
          "La destinee",
          "Malediction",
          "Aventure miniature",
          "Ne tirez pas sur le messager",
          "Frais de porc inclus",
          "A plus dans l'muldobus",
          "Nos amies les betes",
          "La valse des manuels",
          "Shyriiwook",
          "A armes egales",
          "Il a fui, il a tout compris",
          "La peche aux infos",
          "Il y a de l'electricite dans l'eau",
          "Topo le petit robot",
          "Piege de crystal",
          "Son nom est personne",
        ],
      },
    ],
  },
  {
    dofusSlug: "dofus-argente-scintillant",
    groups: [
      {
        subSection: "Prérequis - Quatre sur six",
        questNames: [
          "L'ombre et la proie",
          "La derniere pierre",
          "Les couts du sort",
          "Une ombre au tableau",
          "Un remede draconien",
          "Le dragon des vents",
          "Le dragon des flammes",
          "Le dragon des forets",
          "Le dragon des eaux",
          "Mississitudes",
          "Le destin de kalisthe",
        ],
      },
    ],
  },
  {
    dofusSlug: "dofus-cauchemar",
    groups: [
      {
        subSection: "Prérequis - Début",
        questNames: [
          "L'anneau de tous les dangers",
          "Sous le regard des dieux",
          "Réponse a tout",
          "Le village dans les nuages",
          "Espoirs et tragedies",
          "Dans la gueule du milimulou",
          "Destination Astrub",
          "Les principes d'archie m'aident",
          "On marche sur des oeufs",
          "Conseil de classe",
          "Quete de classe",
          "Ca sent le gaz",
          "Balade en foret",
          "Le reveil de pandala",
          "Dites le avec des fleurs",
          "Un pendule pour guider ses pas",
          "Le receptacle des dofus",
          "Intrusion chez les wabbits",
          "Un sage parmi les sages",
          "Protection divine",
          "Voir le dark vlad et mourir... ou pas",
          "La magicienne des marecages",
          "Retourner voir le dark vlad, toujours sans mourir",
          "Qui botte le cul des culs bottes ?",
          "Le voleur d'ames",
          "Ca est frugal, une fois",
          "C'est tout simple",
          "Arak-hai en pagaille",
          "Munster leve le mystere",
          "L'art de la langue de bois",
        ],
      },
      {
        subSection: "Prérequis - Eliocalypse : Resilience",
        questNames: [
          "A la croisée des mondes",
          "Sous le bois de sa colere",
          "Au nom de l'art",
          "La jetee des enfants perdus",
          "Le festival de la lanterne",
          "L'equilibre des forces",
          "Sang d'encre",
          "Maudite disparition",
          "Requiem pour un yokai",
          "Si loin, si proches",
          "Jusqu'a leur dernier soupir",
          "Main dans la main",
          "En ce jardin qui nous unit",
          "Veilleur sous surveillance",
          "La source de tous les maux",
          "Quand l'eveil n'est qu'un songe",
          "Une bien etrange prophetie",
          "Le dernier rempart",
          "Par ce serment s'ecrit le monde",
          "Deux souffles, une inspiration",
        ],
      },
      {
        subSection: "Prérequis - Encore",
        questNames: [
          "Infame pourriture",
          "Le saule du Promeneur",
          "L'epopee du moine pelerin",
          "De l'encre spectaculaire",
          "Au detour d'un reve perdu",
          "Barnabé dans l'espace",
        ],
      },
      {
        subSection: "Prérequis - Eliocalypse : Resonnance",
        questNames: [
          "Chaque chose en son temps",
          "Aux frontieres du reel",
          "Ce sera mieux avant",
          "Cauchemars premonitoires",
          "Partie de chasse",
          "Quatre contre un",
          "Reves translucides",
        ],
      },
      {
        subSection: "Prérequis - Encore et encore",
        questNames: [
          "Bucherons en detresse",
          "Voyage, voyage",
          "La porte d'enutrosor",
          "Orichomania",
          "La cite de l'indicible mal",
          "Messager clandestin",
          "La voix de son maitre",
          "Le maitre des zaaps",
          "Energie renouvelable",
          "Traitement de choc",
          "Le disparu de sufokia",
          "Rendez-vous avec la mort",
          "Crise d'identite",
        ],
      },
      {
        subSection: "Prérequis - Ravagés",
        questNames: [
          "Toute possession depossede",
          "Le chant du Pandamonium",
          "Le debut de la fin",
        ],
      },
      {
        subSection: "Prérequis - La fin",
        questNames: [
          "Le poids de son regard",
          "L'accuse de la reception",
          "Les monstres aboient, la diligence casse",
          "Chachyene de vie",
          "Les sentiers de la guerre",
          "Legende d'automne",
          "La colere des dieux",
          "Aventure miniature",
          "Ne tirez pas sur le messager",
          "A la rescousse des magypus",
          "Dernier contact",
          "La voix des morts",
          "Le fleau de burin",
          "Le navire aux esclaves",
          "Briser ses chaines",
          "Une boite pour les asservir tous",
          "Le vent se leve",
          "Tournent les vents",
          "Les racines du mal",
          "Un pouvoir merydique",
          "Le jour le plus long",
          "Mort et renouveau",
          "Avis de tempete",
          "Au-dela de la gloire",
          "Voyage au bout de l'externam",
          "Les quatre volontes",
          "Casse en enutrosor",
          "L'avis de la Mort",
          "La guerre de cania n'aura pas lieu",
          "Prise de conscience",
        ],
      },
    ],
  },
  {
    dofusSlug: "dom-de-pin",
    groups: [
      {
        subSection: "Prérequis des prérequis",
        questNames: [
          "Ca est frugal, une fois",
          "Dites le avec des fleurs",
          "Infame pourriture",
          "Le saule du Promeneur",
          "C'est tout simple",
          "Arak-hai en pagaille",
          "Munster leve le mystere",
          "L'art de la langue de bois",
          "A la croisée des mondes",
          "Sous le bois de sa colere",
          "Au nom de l'art",
          "La jetee des enfants perdus",
          "Le festival de la lanterne",
          "L'equilibre des forces",
          "Sang d'encre",
          "Maudite disparition",
          "Requiem pour un yokai",
          "Si loin, si proches",
          "Jusqu'a leur dernier soupir",
          "L'epopee du moine pelerin",
          "Main dans la main",
          "De l'encre spectaculaire",
          "Deux souffles une inspiration",
          "En ce jardin qui nous unit",
          "Barnabe dans l'espace",
          "Chaque chose en son temps",
          "Aux frontieres du reel",
          "Ce sera mieux avant",
          "Cauchemars premonitoires",
          "Partie de chasse",
          "Quatre contre un",
          "Reves translucides",
          "Veilleur sous surveillance",
          "La source de tous les maux",
          "Quand l'eveil n'est qu'un songe",
          "Le dernier rempart",
          "Par ce serment s'ecrit le monde",
          "Une bien etrange prophetie",
          "Bucherons en detresse",
          "Voyage, voyage",
          "La porte d'enutrosor",
          "Orichomania",
          "La cite de l'indicible mal",
          "Messager clandestin",
          "La voix de son maitre",
          "Le maitre des zaaps",
          "Energie renouvelable",
          "Traitement de choc",
          "Le disparu de sufokia",
          "Rendez-vous avec la mort",
          "Crise d'identite",
          "Toute possession depossede",
          "Le chant du Pandamonium",
          "Le debut de la fin",
          "Le poids de son regard",
          "La danse de la dissonance",
          "Descendre aux cendres",
          "L'accuse de la reception",
          "Les monstres aboient, la diligence casse",
          "Chachyene de vie",
          "Les sentiers de la guerre",
          "Les quatre volontes",
          "Prise de conscience",
          "Attention à la bête !",
          "Le nouveau monde",
          "L'ile des naufrages",
          "Protéger et sévir",
          "Le Dofus et l'Alchimiste",
          "La raison du plus fort",
          "Après lui, le déluge",
          "Comme un corbac sur sa branche",
          "Rester planté là",
          "Arrête-la si tu peux",
          "Pas de fumée sans feu",
          "Quand les esprits s'échauffent",
          "Le serment de l'ambre",
        ],
      },
      {
        subSection: "Prérequis - Quatre sur six",
        questNames: [
          "L'ombre et la proie",
          "La derniere pierre",
          "Les couts du sort",
          "Une ombre au tableau",
          "Un remede draconien",
          "Le dragon des vents",
          "Le dragon des flammes",
          "Le dragon des forets",
          "Le dragon des eaux",
          "Mississitudes",
          "Le destin de kalisthe",
        ],
      },
      {
        subSection: "Prérequis - Six sur six",
        questNames: [
          "Dans la gueule du dragon",
          "S'armer contre le destin",
          "La fin... ou le commencement",
        ],
      },
      {
        subSection: "Prérequis - Le secret des Dofus: Prologue",
        questNames: [
          "Au detour d'un reve perdu",
          "Entretemps, une renaissance",
          "La bête au bois dormant",
        ],
      },
      {
        subSection: "100% quêtes Valonia : L'héritage de l'île brisée",
        questNames: [
          "Dis, scierie ?",
          "Colonie de vaillance",
          "Dans la gueule du Trankilou",
          "Association de fureteurs",
          "La complote de P.O.M.S",
          "Un événement inattendu",
          "L'île maudite",
          "Chercher un Marteau-Aigri dans une galerie d'Ereboria",
          "La fin des maningances",
          "La sorcière exilée",
          "Les risques du métier",
          "La graine de la révolte",
          "Par l'héritage qui vous lie",
          "Pour que la flamme vacille",
          "Une dernière volonté",
          "L'heure des adieux",
        ],
      },
    ],
  },
  {
    dofusSlug: "dofus-sylvestre",
    groups: [
      {
        subSection: "Prérequis globaux",
        questNames: [
          "Gobstination d'un Grobelin",
          "Dites le avec des fleurs",
          "Le saule du Promeneur",
          "Infame pourriture",
          "Les racines du mal",
          "Un pouvoir merydique",
          "Mort et renouveau",
        ],
      },
      {
        subSection: "Prérequis frigost",
        questNames: [
          "La terre banquise",
          "La maire de glace",
          "Bienvenue a frigost",
          "Les monologues du vaccin",
          "Antiroyaliste",
          "Bricole girl",
          "Hotel de glace",
          "Epis d'Emi",
          "La fonte des glaces",
          "Promenons-nous dans les bois",
          "L'ombre et la glace",
          "Les joyeux de la couronne",
          "Les chasseurs",
          "La marche de l'imperatrice",
          "Lumiere sur l'ombre",
          "L'essentiel est dans le lac gelé",
          "Il préfère la mort en mer",
          "Fais dodo, t'auras du gâteau",
          "Chauffage a moindre frais",
          "A la recherche de dan lavy",
          "Lavomatique",
          "A qui profite le boufmouth",
          "C'est frais, mais c'est pas grave",
          "Depot de ravitaillement",
          "Chaud du s.l.i.p.",
          "Entrainement avec Tarche",
          "La destinee",
          "Malediction",
          "Sans ma barbe, quelle barbe",
          "Un ami qui ne vous veut pas que du bien",
          "Mission solution",
          "Chaud et froid",
          "Le givre des revelations",
          "Le travail c'est la santé",
        ],
      },
    ],
  },
];

/**
 * Flat lookup map: dofusSlug -> questSlug -> subSection
 * Built once at module load time.
 */
export const SUB_SECTION_LOOKUP: ReadonlyMap<string, ReadonlyMap<string, string>> = (() => {
  const outer = new Map<string, Map<string, string>>();
  for (const entry of RAW_OVERRIDES) {
    const inner = new Map<string, string>();
    for (const group of entry.groups) {
      for (const questName of group.questNames) {
        inner.set(nameToSlug(questName), group.subSection);
      }
    }
    outer.set(entry.dofusSlug, inner);
  }
  return outer;
})();

/**
 * Look up the sub-section override for a given dofus+quest combination.
 * Returns null if no override is defined (default: no sub-section).
 */
export function getSubSection(dofusSlug: string, questSlug: string): string | null {
  return SUB_SECTION_LOOKUP.get(dofusSlug)?.get(questSlug) ?? null;
}
