import { nameToSlug } from "./utils.js";

/**
 * Manual overrides for dofuspourlesnoobs_url when the auto-generated URL
 * (based on nameToSlug) doesn't match the actual page on dofuspourlesnoobs.com.
 *
 * Generated from quete_et_lien.json — 211 overrides.
 */
const RAW_OVERRIDES: Array<{ questName: string; url: string }> = [
  { questName: "A l'endroit, à l'envers", url: "https://www.dofuspourlesnoobs.com/agrave-lendroit-agrave-lenvers.html" },
  { questName: "A vol d'oiseau", url: "https://www.dofuspourlesnoobs.com/agrave-vol-doiseau.html" },
  { questName: "Aller voir le Dieu Sram", url: "https://www.dofuspourlesnoobs.com/srambad.html" },
  { questName: "Aller voir le Dieu Xelor", url: "https://www.dofuspourlesnoobs.com/xeacutelorium.html" },
  { questName: "Amayiro à l'ombre du Champo", url: "https://www.dofuspourlesnoobs.com/amayiro-agrave-lombre-du-champo.html" },
  { questName: "Apprentissage : Adepte des Douleurs", url: "https://www.dofuspourlesnoobs.com/apprentissage--adepte-des-douleurs.html" },
  { questName: "Apprentissage : Apprenti sombre", url: "https://www.dofuspourlesnoobs.com/apprentissage--apprenti-sombre.html" },
  { questName: "Apprentissage : Disciple d'hecate", url: "https://www.dofuspourlesnoobs.com/apprentissage--disciple-dheacutecate.html" },
  { questName: "Apprentissage : Gardien des tortures", url: "https://www.dofuspourlesnoobs.com/apprentissage--gardien-des-tortures.html" },
  { questName: "Apprentissage : Maitre des sevices", url: "https://www.dofuspourlesnoobs.com/apprentissage--maicirctre-des-seacutevices.html" },
  { questName: "Arak-hai en pagaille", url: "https://www.dofuspourlesnoobs.com/arak-haiuml-en-pagaille.html" },
  { questName: "Au-dela du mur", url: "https://www.dofuspourlesnoobs.com/au-delagrave-du-mur.html" },
  { questName: "Aujourd'hui a jamais", url: "https://www.dofuspourlesnoobs.com/aujourdhui-agrave-jamais.html" },
  { questName: "Aux grands mots les grands remedes", url: "https://www.dofuspourlesnoobs.com/aux-grands-mots-les-grands-remegravedes.html" },
  { questName: "Avoir le sort apprivoisement de monture", url: "https://www.dofuspourlesnoobs.com/sorts-communs.html#capture-ames" },
  { questName: "Avoir le sort capture d'ames", url: "https://www.dofuspourlesnoobs.com/sorts-communs.html#capture-ames" },
  { questName: "Bien velu c'est kerubim", url: "https://www.dofuspourlesnoobs.com/bien-velu-cest-kerubim.html" },
  { questName: "Bienvenue a frigost", url: "https://www.dofuspourlesnoobs.com/bienvenue-agrave-frigost.html" },
  { questName: "C'est dans la boite", url: "https://www.dofuspourlesnoobs.com/cest-dans-la-boicircte.html" },
  { questName: "C'est frais, mais c'est pas grave", url: "https://www.dofuspourlesnoobs.com/cest-frais-mais-cest-pas-grave.html" },
  { questName: "C'est quoi ton 06", url: "https://www.dofuspourlesnoobs.com/cest-quoi-ton-06.html" },
  { questName: "C'est stupefiant", url: "https://www.dofuspourlesnoobs.com/cest-stupeacutefiant.html" },
  { questName: "C'est ton destin", url: "https://www.dofuspourlesnoobs.com/cest-ton-destin.html" },
  { questName: "C'est tout simple", url: "https://www.dofuspourlesnoobs.com/cest-tout-simple.html" },
  { questName: "Ca katche ou ca casse", url: "https://www.dofuspourlesnoobs.com/ccedila-katche-ou-ccedila-casse.html" },
  { questName: "Ca se katche", url: "https://www.dofuspourlesnoobs.com/ccedila-se-katche.html" },
  { questName: "Ca sent la cawotte", url: "https://www.dofuspourlesnoobs.com/ccedila-sent-la-cawotte.html" },
  { questName: "Cartes spéciales d'Amayiro", url: "https://www.dofuspourlesnoobs.com/cartes-speacuteciales-damayiro.html" },
  { questName: "Celle qui glougloutait dans les tenebres", url: "https://www.dofuspourlesnoobs.com/celle-qui-glougloutait-dans-les-teacutenegravebres.html" },
  { questName: "Chachyene de vie", url: "https://www.dofuspourlesnoobs.com/chachyegravene-de-vie.html" },
  { questName: "Champ borde le chateau", url: "https://www.dofuspourlesnoobs.com/champ-borde-le-chacircteau.html" },
  { questName: "Chaud du s.l.i.p.", url: "https://www.dofuspourlesnoobs.com/chaud-du-slip.html" },
  { questName: "Chauffage a moindre frais", url: "https://www.dofuspourlesnoobs.com/chauffage-agrave-moindre-frais.html" },
  { questName: "Comme un poison dans l'eau", url: "https://www.dofuspourlesnoobs.com/comme-un-poison-dans-leau.html" },
  { questName: "Concurrence deloyale", url: "https://www.dofuspourlesnoobs.com/concurrence-deacuteloyale.html" },
  { questName: "Corvee de patate", url: "https://www.dofuspourlesnoobs.com/corveacutee-de-patate.html" },
  { questName: "Coups d'epee dans l'eau", url: "https://www.dofuspourlesnoobs.com/coups-deacutepeacutee-dans-leau.html" },
  { questName: "Courir apres des ombres", url: "https://www.dofuspourlesnoobs.com/courir-apregraves-des-ombres.html" },
  { questName: "Crise d'ex-emma", url: "https://www.dofuspourlesnoobs.com/crise-dex-emma.html" },
  { questName: "Crise d'identite", url: "https://www.dofuspourlesnoobs.com/crise-didentiteacute.html" },
  { questName: "D'egouts temps", url: "https://www.dofuspourlesnoobs.com/deacutegouts-temps.html" },
  { questName: "Dans la gueule du milimulou", url: "https://www.dofuspourlesnoobs.com/dans-la-gueule-du-milimilou.html" },
  { questName: "Dapyus n'est pas doue", url: "https://www.dofuspourlesnoobs.com/dapyus-nest-pas-doueacute.html" },
  { questName: "De la poudre aux yeux de Brâkmar", url: "https://www.dofuspourlesnoobs.com/de-la-poudre-aux-yeux-de-bracirckmar.html" },
  { questName: "Dechirures temporelles", url: "https://www.dofuspourlesnoobs.com/deacutechirures-temporelles.html" },
  { questName: "Decime-moi des bouftous", url: "https://www.dofuspourlesnoobs.com/deacutecime-moi-des-bouftous.html" },
  { questName: "Demain, j'arrete", url: "https://www.dofuspourlesnoobs.com/demain-jarecircte.html" },
  { questName: "Dephorrestation", url: "https://www.dofuspourlesnoobs.com/deacutephorrestation.html" },
  { questName: "Depot de ravitaillement", url: "https://www.dofuspourlesnoobs.com/deacutepocirct-de-ravitaillement.html" },
  { questName: "Depuis l'enfer", url: "https://www.dofuspourlesnoobs.com/depuis-lenfer.html" },
  { questName: "Des combats pas tres legaux", url: "https://www.dofuspourlesnoobs.com/des-combats-pas-tregraves-leacutegaux.html" },
  { questName: "Des pwinces pas tres charmants", url: "https://www.dofuspourlesnoobs.com/des-pwinces-pas-tregraves-charmants.html" },
  { questName: "Des vestiges de legende", url: "https://www.dofuspourlesnoobs.com/des-vestiges-de-leacutegende.html" },
  { questName: "Developpement durable", url: "https://www.dofuspourlesnoobs.com/deacuteveloppement-durable.html" },
  { questName: "Donjon et trouffions", url: "https://www.dofuspourlesnoobs.com/donjons-et-trouffions.html" },
  { questName: "Echantillonnage", url: "https://www.dofuspourlesnoobs.com/eacutechantillonnage.html" },
  { questName: "Energie renouvelable", url: "https://www.dofuspourlesnoobs.com/eacutenergie-renouvelable.html" },
  { questName: "Entrainement avec Tarche", url: "https://www.dofuspourlesnoobs.com/entraicircnement-avec-tarche.html" },
  { questName: "Entrainement avec Torche", url: "https://www.dofuspourlesnoobs.com/entraicircnement-avec-torche.html" },
  { questName: "Epidemiologie", url: "https://www.dofuspourlesnoobs.com/eacutepideacutemiologie.html" },
  { questName: "Epis d'Emi", url: "https://www.dofuspourlesnoobs.com/eacutepis-demi.html" },
  { questName: "Espoirs et tragedies", url: "https://www.dofuspourlesnoobs.com/espoirs-et-trageacutedies.html" },
  { questName: "Expedition culinaire", url: "https://www.dofuspourlesnoobs.com/expeacutedition-culinaire.html" },
  { questName: "Fais dodo, t'auras du gâteau", url: "https://www.dofuspourlesnoobs.com/fais-dodo-tauras-du-gacircteau.html" },
  { questName: "Faites l'amour, pas la guerre", url: "https://www.dofuspourlesnoobs.com/faites-lamour-pas-la-guerre.html" },
  { questName: "Frigost, une ile pas comme les autres", url: "https://www.dofuspourlesnoobs.com/frigost-une-icircle-pas-comme-les-autres.html" },
  { questName: "Futur anterieur", url: "https://www.dofuspourlesnoobs.com/futur-anteacuterieur.html" },
  { questName: "Hotel de glace", url: "https://www.dofuspourlesnoobs.com/hocirctel-de-glace.html" },
  { questName: "Il etait une foi dans l'ouest", url: "https://www.dofuspourlesnoobs.com/il-eacutetait-une-foi-dans-louest.html" },
  { questName: "Il faut mettre un terme aux maitres", url: "https://www.dofuspourlesnoobs.com/il-faut-mettre-un-terme-aux-maicirctres.html" },
  { questName: "Il préfère la mort en mer", url: "https://www.dofuspourlesnoobs.com/il-preacutefegravere-la-mort-en-mer.html" },
  { questName: "Il suffira d'un signe", url: "https://www.dofuspourlesnoobs.com/il-suffira-dun-signe.html" },
  { questName: "Il y a de l'electricite dans l'eau", url: "https://www.dofuspourlesnoobs.com/il-y-a-de-leacutelectriciteacute-dans-leau.html" },
  { questName: "Je panse donc j'essuie", url: "https://www.dofuspourlesnoobs.com/je-panse-donc-jessuie.html" },
  { questName: "L'accuse de la reception", url: "https://www.dofuspourlesnoobs.com/laccuseacute-de-la-reacuteception.html" },
  { questName: "L'affaire pollie perkine", url: "https://www.dofuspourlesnoobs.com/laffaire-pollie-perkine.html" },
  { questName: "L'amour perdu de nabur", url: "https://www.dofuspourlesnoobs.com/lamour-perdu-de-nabur.html" },
  { questName: "L'anneau de tot", url: "https://www.dofuspourlesnoobs.com/lanneau-de-tot.html" },
  { questName: "L'année du dragon", url: "https://www.dofuspourlesnoobs.com/lanneacutee-du-dragon.html" },
  { questName: "L'armee des 12 dingues", url: "https://www.dofuspourlesnoobs.com/larmeacutee-des-12-dingues.html" },
  { questName: "L'art de la langue de bois", url: "https://www.dofuspourlesnoobs.com/lart-de-la-langue-de-bois.html" },
  { questName: "L'art me ment", url: "https://www.dofuspourlesnoobs.com/lart-me-ment.html" },
  { questName: "L'effet paula rice", url: "https://www.dofuspourlesnoobs.com/leffet-paula-rice.html" },
  { questName: "L'elite squelettique", url: "https://www.dofuspourlesnoobs.com/leacutelite-squelettique.html" },
  { questName: "L'essentiel est dans le lac gelé", url: "https://www.dofuspourlesnoobs.com/lessentiel-est-dans-le-lac-geleacute.html" },
  { questName: "L'etendue godelique", url: "https://www.dofuspourlesnoobs.com/leacutetendue-goumldelique.html" },
  { questName: "L'eternel moisson", url: "https://www.dofuspourlesnoobs.com/leacuteternelle-moisson.html" },
  { questName: "L'eternelle moisson", url: "https://www.dofuspourlesnoobs.com/leacuteternelle-moisson.html" },
  { questName: "L'ile des naufrages", url: "https://www.dofuspourlesnoobs.com/licircle-des-naufrageacutes.html" },
  { questName: "L'ivresse des profondeurs", url: "https://www.dofuspourlesnoobs.com/livresse-des-profondeurs.html" },
  { questName: "L'odeur devant le seuil", url: "https://www.dofuspourlesnoobs.com/lodeur-devant-le-seuil.html" },
  { questName: "L'oeuf ou la cawotte ?", url: "https://www.dofuspourlesnoobs.com/lrsquooeliguf-ou-la-cawotte.html" },
  { questName: "L'ombre et la glace", url: "https://www.dofuspourlesnoobs.com/lombre-et-la-glace.html" },
  { questName: "L'ombre et la proie", url: "https://www.dofuspourlesnoobs.com/lombre-et-la-proie.html" },
  { questName: "La benediction de foluk", url: "https://www.dofuspourlesnoobs.com/la-beacuteneacutediction-de-foluk.html" },
  { questName: "La benediction de thomahon", url: "https://www.dofuspourlesnoobs.com/la-beacuteneacutediction-de-thomahon.html" },
  { questName: "La benediction de viti", url: "https://www.dofuspourlesnoobs.com/la-beacuteneacutediction-de-viti.html" },
  { questName: "La cite de l'indicible mal", url: "https://www.dofuspourlesnoobs.com/la-citeacute-de-lindicible-mal.html" },
  { questName: "La clef de l'enigme", url: "https://www.dofuspourlesnoobs.com/la-clef-de-leacutenigme.html" },
  { questName: "La complote de P.O.M.S", url: "https://www.dofuspourlesnoobs.com/la-complote-des-poms.html" },
  { questName: "La derniere carte", url: "https://www.dofuspourlesnoobs.com/la-derniegravere-carte.html" },
  { questName: "La fatalite", url: "https://www.dofuspourlesnoobs.com/la-fataliteacute-prologue.html" },
  { questName: "La fifille a son papa", url: "https://www.dofuspourlesnoobs.com/la-fifille-agrave-son-papa.html" },
  { questName: "La foire du Trool suspectee", url: "https://www.dofuspourlesnoobs.com/la-foire-du-trool-suspecteacutee.html" },
  { questName: "La fureur du Holbaid", url: "https://www.dofuspourlesnoobs.com/la-fureur-du-holbaiumld.html" },
  { questName: "La galette secrete", url: "https://www.dofuspourlesnoobs.com/la-galette-secregravete.html" },
  { questName: "La greve de la fin", url: "https://www.dofuspourlesnoobs.com/la-gregraveve-de-la-fin.html" },
  { questName: "La gueule de l'enfer", url: "https://www.dofuspourlesnoobs.com/la-gueule-de-lenfer.html" },
  { questName: "La machine a demonter le temps", url: "https://www.dofuspourlesnoobs.com/la-machine-agrave-deacutemonter-le-temps.html" },
  { questName: "La magicienne des marecages", url: "https://www.dofuspourlesnoobs.com/la-magicienne-des-mareacutecages.html" },
  { questName: "La marche de l'imperatrice", url: "https://www.dofuspourlesnoobs.com/la-marche-de-limpeacuteratrice.html" },
  { questName: "La mechante sorciere de l'est", url: "https://www.dofuspourlesnoobs.com/la-meacutechante-sorciegravere-de-lest.html" },
  { questName: "La meilleure defense, c'est l'attaque", url: "https://www.dofuspourlesnoobs.com/la-meilleure-deacutefense-cest-lattaque.html" },
  { questName: "La mort dans l'ame", url: "https://www.dofuspourlesnoobs.com/le-mort-dans-l-ame.html" },
  { questName: "La morte adele", url: "https://www.dofuspourlesnoobs.com/la-morte-adegravele.html" },
  { questName: "La peche a mel", url: "https://www.dofuspourlesnoobs.com/la-pecircche-agrave-mel.html" },
  { questName: "La peche au poison", url: "https://www.dofuspourlesnoobs.com/la-pecircche-au-poison.html" },
  { questName: "La peche aux infos", url: "https://www.dofuspourlesnoobs.com/la-pecircche-aux-infos.html" },
  { questName: "La pelle de la phorree", url: "https://www.dofuspourlesnoobs.com/la-pelle-de-la-phorreacutee.html" },
  { questName: "La porte d'enutrosor", url: "https://www.dofuspourlesnoobs.com/la-porte-denutrosor.html" },
  { questName: "La quatrieme dimension", url: "https://www.dofuspourlesnoobs.com/la-quatriegraveme-dimension.html" },
  { questName: "La serveuse Dame Cloude", url: "https://www.dofuspourlesnoobs.com/la-tenanciegravere-dame-cloude.html" },
  { questName: "La verite est au fond du puits", url: "https://www.dofuspourlesnoobs.com/la-veacuteriteacute-est-au-fond-du-puits.html" },
  { questName: "La vie de chateau", url: "https://www.dofuspourlesnoobs.com/la-vie-de-chacircteau.html" },
  { questName: "La vie l'hormonde et le reste", url: "https://www.dofuspourlesnoobs.com/la-vie-lhormonde-et-le-reste.html" },
  { questName: "La voix de son maitre", url: "https://www.dofuspourlesnoobs.com/la-voix-de-son-maicirctre.html" },
  { questName: "La-haut sur la montagne", url: "https://www.dofuspourlesnoobs.com/lagrave-haut-sur-la-montagne.html" },
  { questName: "Laisse en plan", url: "https://www.dofuspourlesnoobs.com/laisseacute-en-plan.html" },
  { questName: "Le Tabi d'Amayiro", url: "https://www.dofuspourlesnoobs.com/le-tabi-damayiro.html" },
  { questName: "Le champ des heros", url: "https://www.dofuspourlesnoobs.com/le-champ-des-heacuteros.html" },
  { questName: "Le chateau du wa", url: "https://www.dofuspourlesnoobs.com/le-chacircteau-du-wa.html" },
  { questName: "Le deces de Rimaraf", url: "https://www.dofuspourlesnoobs.com/le-deacutecegraves-de-rimaraf.html" },
  { questName: "Le dragon des forets", url: "https://www.dofuspourlesnoobs.com/le-dragon-des-foret.html" },
  { questName: "Le fantôme de Tsog", url: "https://www.dofuspourlesnoobs.com/le-fantocircme-de-tsog.html" },
  { questName: "Le givre des revelations", url: "https://www.dofuspourlesnoobs.com/le-givre-des-reacuteveacutelations.html" },
  { questName: "Le hero de sufokia", url: "https://www.dofuspourlesnoobs.com/le-heros-de-sufokia.html" },
  { questName: "Le maitre des zaaps", url: "https://www.dofuspourlesnoobs.com/le-maicirctre-des-zaaps.html" },
  { questName: "Le pouvoir derriere le trone", url: "https://www.dofuspourlesnoobs.com/le-pouvoir-derriegravere-le-trocircne.html" },
  { questName: "Le repos est dans le champs", url: "https://www.dofuspourlesnoobs.com/le-repos-est-dans-le-champ.html" },
  { questName: "Le safari des ames", url: "https://www.dofuspourlesnoobs.com/le-safari-des-acircmes.html" },
  { questName: "Le silence est d'or", url: "https://www.dofuspourlesnoobs.com/le-silence-est-dor.html" },
  { questName: "Le travail c'est la santé", url: "https://www.dofuspourlesnoobs.com/le-travail-cest-la-santeacute.html" },
  { questName: "Le tresor de totankama", url: "https://www.dofuspourlesnoobs.com/le-treacutesor-de-totankama.html" },
  { questName: "Le voleur d'ames", url: "https://www.dofuspourlesnoobs.com/le-voleur-dacircmes.html" },
  { questName: "Lecon d'humilite", url: "https://www.dofuspourlesnoobs.com/leccedilon-dhumiliteacute.html" },
  { questName: "Lecon de cuisine", url: "https://www.dofuspourlesnoobs.com/leccedilon-de-cuisine.html" },
  { questName: "Les demons de midi", url: "https://www.dofuspourlesnoobs.com/les-deacutemons-de-midi.html" },
  { questName: "Les derniers rescapes", url: "https://www.dofuspourlesnoobs.com/les-derniers-rescapeacutes.html" },
  { questName: "Les mercemers sont bien outilles", url: "https://www.dofuspourlesnoobs.com/les-mercemers-sont-bien-outilleacutes.html" },
  { questName: "Les rescapes du village enseveli", url: "https://www.dofuspourlesnoobs.com/les-rescapeacutes-du-village-enseveli.html" },
  { questName: "Les rescapés de frigost", url: "https://www.dofuspourlesnoobs.com/les-rescapeacutes-de-frigost.html" },
  { questName: "Lumiere sur l'ombre", url: "https://www.dofuspourlesnoobs.com/lumiegravere-sur-lombre.html" },
  { questName: "Lyeno, Abraknyde malgre lui", url: "https://www.dofuspourlesnoobs.com/lyeno-abraknyde-malgreacute-lui.html" },
  { questName: "Malediction", url: "https://www.dofuspourlesnoobs.com/maleacutediction.html" },
  { questName: "Maudite generosite", url: "https://www.dofuspourlesnoobs.com/maudite-geacuteneacuterositeacute.html" },
  { questName: "Memoires d'outre-tombe", url: "https://www.dofuspourlesnoobs.com/meacutemoires-doutre-tombe.html" },
  { questName: "Memoires d'un amnesique", url: "https://www.dofuspourlesnoobs.com/meacutemoires-dun-amneacutesique.html" },
  { questName: "Mieux vaut ne pas se fier a la premiere impresssion", url: "https://www.dofuspourlesnoobs.com/mieux-vaut-ne-pas-se-fier-a-la-premiere-impression.html" },
  { questName: "Mise a l'epreuve", url: "https://www.dofuspourlesnoobs.com/mise-agrave-leacutepreuve.html" },
  { questName: "Mission de reconnaissance au cimetiere", url: "https://www.dofuspourlesnoobs.com/mission-de-reconnaissance-au-cimetiegravere.html" },
  { questName: "Moteur a explosion", url: "https://www.dofuspourlesnoobs.com/moteur-agrave-explosion.html" },
  { questName: "Munster leve le mystere", url: "https://www.dofuspourlesnoobs.com/munster-legraveve-le-mystegravere.html" },
  { questName: "Naissance d'une vocation", url: "https://www.dofuspourlesnoobs.com/naissance-dune-vocation.html" },
  { questName: "Necrotiques, tiques, tiques", url: "https://www.dofuspourlesnoobs.com/neacutecrotiques-tiques-tiques.html" },
  { questName: "On ne prete qu'a richard", url: "https://www.dofuspourlesnoobs.com/on-ne-precircte-quagrave-richard.html" },
  { questName: "Parler au Dieu Enutrof", url: "https://www.dofuspourlesnoobs.com/enutrosor.html" },
  { questName: "Pas de fainéants dans les rangs", url: "https://www.dofuspourlesnoobs.com/pas-de-faineacuteants-dans-les-rangs.html" },
  { questName: "Peche aux krabouilleurs", url: "https://www.dofuspourlesnoobs.com/pecircche-aux-krabouilleurs.html" },
  { questName: "Peche en eaux gelees", url: "https://www.dofuspourlesnoobs.com/pecircche-en-eaux-geleacutees.html" },
  { questName: "Piege de crystal", url: "https://www.dofuspourlesnoobs.com/piegravege-de-crystal.html" },
  { questName: "Plongeaon et dragon", url: "https://www.dofuspourlesnoobs.com/plongeon-et-dragon.html" },
  { questName: "Pomdeupin vaut mieux que trois tu l'auras", url: "https://www.dofuspourlesnoobs.com/pomdeupin-vaut-mieux-que-trois-tu-lauras.html" },
  { questName: "Pompe a fric", url: "https://www.dofuspourlesnoobs.com/pompe-agrave-fric.html" },
  { questName: "Pot l'agent double", url: "https://www.dofuspourlesnoobs.com/pot-lagent-double.html" },
  { questName: "Premiere visite a Brakmar", url: "https://www.dofuspourlesnoobs.com/premiegravere-visite-agrave-bracirckmar.html" },
  { questName: "Presume coupable", url: "https://www.dofuspourlesnoobs.com/preacutesumeacute-coupable.html" },
  { questName: "Prise d'otage", url: "https://www.dofuspourlesnoobs.com/prise-dotages.html" },
  { questName: "Protéger et sévir", url: "https://www.dofuspourlesnoobs.com/proteacuteger-et-seacutevir.html" },
  { questName: "Qui botte le cul des culs bottes ?", url: "https://www.dofuspourlesnoobs.com/qui-botte-le-cul-des-culs-botteacutes.html" },
  { questName: "Rancon nage", url: "https://www.dofuspourlesnoobs.com/ranccedilon-nage.html" },
  { questName: "Rappel à la vie", url: "https://www.dofuspourlesnoobs.com/rappel-agrave-la-vie.html" },
  { questName: "Recouvrement de dette à la Tabasse", url: "https://www.dofuspourlesnoobs.com/recouvrement-de-dette-agrave-la-tabasse.html" },
  { questName: "Regrets d'eternailes", url: "https://www.dofuspourlesnoobs.com/regrets-deacuteternailes.html" },
  { questName: "Reine de beaute", url: "https://www.dofuspourlesnoobs.com/reine-de-beauteacute.html" },
  { questName: "Repaire du Skeunk", url: "https://www.dofuspourlesnoobs.com/repaire-de-skeunk.html" },
  { questName: "Retour vers le present", url: "https://www.dofuspourlesnoobs.com/retour-vers-le-preacutesent.html" },
  { questName: "Réponse a tout", url: "https://www.dofuspourlesnoobs.com/reacuteponses-agrave-tout.html" },
  { questName: "S'emparer des commandes", url: "https://www.dofuspourlesnoobs.com/semparer-des-commandes.html" },
  { questName: "Sa majeste des necrotiques", url: "https://www.dofuspourlesnoobs.com/sa-majesteacute-des-neacutecrotiques.html" },
  { questName: "Sauvegarder l'espece", url: "https://www.dofuspourlesnoobs.com/sauvegarder-lespegravece.html" },
  { questName: "Scene de menage", url: "https://www.dofuspourlesnoobs.com/scegravene-de-meacutenage.html" },
  { questName: "Sortir de l'ombre", url: "https://www.dofuspourlesnoobs.com/sortir-de-lombre.html" },
  { questName: "Strategie en trithon reel", url: "https://www.dofuspourlesnoobs.com/strateacutegie-en-trithon-reacuteel.html" },
  { questName: "Tabi t'a fleuri", url: "https://www.dofuspourlesnoobs.com/tabi-ta-fleuri.html" },
  { questName: "Taures et detours", url: "https://www.dofuspourlesnoobs.com/taures-et-deacutetours.html" },
  { questName: "Terminutor le jugement de la machine", url: "https://www.dofuspourlesnoobs.com/terminutor--le-jugement-de-la-machine.html" },
  { questName: "Touchez pas a grisebigle", url: "https://www.dofuspourlesnoobs.com/touchez-pas-agrave-grisebigle.html" },
  { questName: "Tout ce qu'il te faut c'est tuer", url: "https://www.dofuspourlesnoobs.com/tout-ce-quil-te-faut-cest-tuer.html" },
  { questName: "Tout ce qui brille n'est pas or", url: "https://www.dofuspourlesnoobs.com/tout-ce-qui-brille-nest-pas-or.html" },
  { questName: "Tresorphelinat", url: "https://www.dofuspourlesnoobs.com/treacutesorphelinat.html" },
  { questName: "Trop pollie pour etre honnete", url: "https://www.dofuspourlesnoobs.com/trop-pollie-pour-ecirctre-honnecircte.html" },
  { questName: "Ultime reminiscence", url: "https://www.dofuspourlesnoobs.com/ultime-reacuteminiscence.html" },
  { questName: "Un coeur d'or", url: "https://www.dofuspourlesnoobs.com/un-coeligur-dor.html" },
  { questName: "Un indigene chez les indigenes", url: "https://www.dofuspourlesnoobs.com/un-indigeste-chez-les-indigegravenes.html" },
  { questName: "Une ame en colere", url: "https://www.dofuspourlesnoobs.com/une-acircme-en-colegravere.html" },
  { questName: "Une ame en peine", url: "https://www.dofuspourlesnoobs.com/une-acircme-en-peine.html" },
  { questName: "Une breche à Bonta", url: "https://www.dofuspourlesnoobs.com/une-bregraveche-agrave-bonta.html" },
  { questName: "Une porte vers le passe", url: "https://www.dofuspourlesnoobs.com/une-porte-vers-le-passeacute.html" },
  { questName: "Vert emeraude", url: "https://www.dofuspourlesnoobs.com/vert-eacutemeraude.html" },
  { questName: "Viande fraiche", url: "https://www.dofuspourlesnoobs.com/viande-fraicircche.html" },
  { questName: "Vous avez demande la peau lisse ?", url: "https://www.dofuspourlesnoobs.com/vous-avez-demandeacute-la-peau-lisse.html" },
];

const URL_LOOKUP = new Map<string, string>(
  RAW_OVERRIDES.map((o) => [nameToSlug(o.questName), o.url])
);

/**
 * Returns the correct dofuspourlesnoobs URL for a quest if an override exists,
 * otherwise returns null (auto-generation will be used).
 */
export function getUrlOverride(questSlug: string): string | null {
  return URL_LOOKUP.get(questSlug) ?? null;
}
