-- ============================================================
-- Dofus Ivoire — insertion quêtes Brakmar + ordres manquants
-- Idempotent : peut être relancé sans risque
-- ============================================================

-- ----------------------------------------------------------------
-- 1. Insérer les quêtes manquantes (si elles n'existent pas)
-- ----------------------------------------------------------------
INSERT INTO quests (name, slug, dofuspourlesnoobs_url) VALUES
  -- Brakmar (100 + 2 bis)
  ('Cliquetis fou',                                'cliquetis-fou',                               'https://www.dofuspourlesnoobs.com/cliquetis-fou.html'),
  ('Le professionnel',                             'le-professionnel',                            'https://www.dofuspourlesnoobs.com/le-professionnel.html'),
  ('Un coup de fouet',                             'un-coup-de-fouet',                            'https://www.dofuspourlesnoobs.com/un-coup-de-fouet.html'),
  ('Le dentiste dement',                           'le-dentiste-dement',                          'https://www.dofuspourlesnoobs.com/le-dentiste-dement.html'),
  ('La revanche de mak',                           'la-revanche-de-mak',                          'https://www.dofuspourlesnoobs.com/la-revanche-de-mak.html'),
  ('La noirceur des armes blanches',               'la-noirceur-des-armes-blanches',              'https://www.dofuspourlesnoobs.com/la-noirceur-des-armes-blanches.html'),
  ('La mise à mort',                               'la-mise-a-mort',                              'https://www.dofuspourlesnoobs.com/la-mise-a-mort.html'),
  ('Les gardes d''honneur... a punir',             'les-gardes-d-honneur-a-punir',                'https://www.dofuspourlesnoobs.com/les-gardes-d-honneur-a-punir.html'),
  ('Un oubli regrettable',                         'un-oubli-regrettable',                        'https://www.dofuspourlesnoobs.com/un-oubli-regrettable.html'),
  ('Tete de gland',                                'tete-de-gland',                               'https://www.dofuspourlesnoobs.com/tete-de-gland.html'),
  ('Pauvre larve',                                 'pauvre-larve',                                'https://www.dofuspourlesnoobs.com/pauvre-larve.html'),
  ('Pauvre larve... doree',                        'pauvre-larve-doree',                          'https://www.dofuspourlesnoobs.com/pauvre-larve-doree.html'),
  ('Agent double et demi',                         'agent-double-et-demi',                        'https://www.dofuspourlesnoobs.com/agent-double-et-demi.html'),
  ('Livreur de mauvaise nouvelle',                 'livreur-de-mauvaise-nouvelle',                'https://www.dofuspourlesnoobs.com/livreur-de-mauvaise-nouvelle.html'),
  ('Une collection digne de Xilebo',               'une-collection-digne-de-xilebo',              'https://www.dofuspourlesnoobs.com/une-collection-digne-de-xilebo.html'),
  ('D''egout pille',                               'd-egout-pille',                               'https://www.dofuspourlesnoobs.com/d-egout-pille.html'),
  ('Le tabi mangeur de blops',                     'le-tabi-mangeur-de-blops',                    'https://www.dofuspourlesnoobs.com/le-tabi-mangeur-de-blops.html'),
  ('Alchimie malfaisante',                         'alchimie-malfaisante',                        'https://www.dofuspourlesnoobs.com/alchimie-malfaisante.html'),
  ('Des capes typiques',                           'des-capes-typiques',                          'https://www.dofuspourlesnoobs.com/des-capes-typiques.html'),
  ('Le testament du papa',                         'le-testament-du-papa',                        'https://www.dofuspourlesnoobs.com/le-testament-du-papa.html'),
  ('Amadouer ou corrompre',                        'amadouer-ou-corrompre',                       'https://www.dofuspourlesnoobs.com/amadouer-ou-corrompre.html'),
  ('Taxe gratuite',                                'taxe-gratuite',                               'https://www.dofuspourlesnoobs.com/taxe-gratuite.html'),
  ('Par la force ou par la finesse',               'par-la-force-ou-par-la-finesse',              'https://www.dofuspourlesnoobs.com/par-la-force-ou-par-la-finesse.html'),
  ('Le dur travail d''eplucheur de patates',       'le-dur-travail-d-eplucheur-de-patates',       'https://www.dofuspourlesnoobs.com/le-dur-travail-d-eplucheur-de-patates.html'),
  ('Cruel, mais à quel point',                     'cruel-mais-a-quel-point',                     'https://www.dofuspourlesnoobs.com/cruel-mais-a-quel-point.html'),
  ('Activites volcaniques',                        'activites-volcaniques',                       'https://www.dofuspourlesnoobs.com/activites-volcaniques.html'),
  ('Chasse a l''espion',                           'chasse-a-l-espion',                           'https://www.dofuspourlesnoobs.com/chasse-a-l-espion.html'),
  ('Un petit oubli',                               'un-petit-oubli',                              'https://www.dofuspourlesnoobs.com/un-petit-oubli.html'),
  ('Du venin sinon rien',                          'du-venin-sinon-rien',                         'https://www.dofuspourlesnoobs.com/du-venin-sinon-rien.html'),
  ('Le defi du maitre guerrier',                   'le-defi-du-maitre-guerrier',                  'https://www.dofuspourlesnoobs.com/le-defi-du-maitre-guerrier.html'),
  ('Joie de courte duree',                         'joie-de-courte-duree',                        'https://www.dofuspourlesnoobs.com/joie-de-courte-duree.html'),
  ('Au combat',                                    'au-combat',                                   'https://www.dofuspourlesnoobs.com/au-combat.html'),
  ('Un assassin... a Bonta',                       'un-assassin-a-bonta',                         'https://www.dofuspourlesnoobs.com/un-assassin-a-bonta.html'),
  ('Un dentier pour l''ami mak',                   'un-dentier-pour-l-ami-mak',                   'https://www.dofuspourlesnoobs.com/un-dentier-pour-l-ami-mak.html'),
  ('Un choix difficile',                           'un-choix-difficile',                          'https://www.dofuspourlesnoobs.com/un-choix-difficile.html'),
  ('Arrivee a bon port',                           'arrivee-a-bon-port',                          'https://www.dofuspourlesnoobs.com/arrivee-a-bon-port.html'),
  ('Humiliation sans precedent',                   'humiliation-sans-precedent',                  'https://www.dofuspourlesnoobs.com/humiliation-sans-precedent.html'),
  ('Opposition aux opposants',                     'opposition-aux-opposants',                    'https://www.dofuspourlesnoobs.com/opposition-aux-opposants.html'),
  ('A la rescousse d''un incapable',               'a-la-rescousse-d-un-incapable',               'https://www.dofuspourlesnoobs.com/a-la-rescousse-d-un-incapable.html'),
  ('Mulanthropie',                                 'mulanthropie',                                'https://www.dofuspourlesnoobs.com/mulanthropie.html'),
  ('Triple x',                                     'triple-x',                                    'https://www.dofuspourlesnoobs.com/triple-x.html'),
  ('X comme xephires',                             'x-comme-xephires',                            'https://www.dofuspourlesnoobs.com/x-comme-xephires.html'),
  ('Operation commando',                           'operation-commando',                          'https://www.dofuspourlesnoobs.com/operation-commando.html'),
  ('Rencontre du premier type',                    'rencontre-du-premier-type',                   'https://www.dofuspourlesnoobs.com/rencontre-du-premier-type.html'),
  ('Joyau... ze fete',                             'joyau-ze-fete',                               'https://www.dofuspourlesnoobs.com/joyau-ze-fete.html'),
  ('Le cristal de kain dharyn',                    'le-cristal-de-kain-dharyn',                   'https://www.dofuspourlesnoobs.com/le-cristal-de-kain-dharyn.html'),
  ('Cambriolage',                                  'cambriolage',                                 'https://www.dofuspourlesnoobs.com/cambriolage.html'),
  ('Livraison rapide',                             'livraison-rapide',                            'https://www.dofuspourlesnoobs.com/livraison-rapide.html'),
  ('Le moment de vérité',                          'le-moment-de-verite',                         'https://www.dofuspourlesnoobs.com/le-moment-de-verite.html'),
  ('Le puits sans fond',                           'le-puits-sans-fond',                          'https://www.dofuspourlesnoobs.com/le-puits-sans-fond.html'),
  ('Le carnage des plaines',                       'le-carnage-des-plaines',                      'https://www.dofuspourlesnoobs.com/le-carnage-des-plaines.html'),
  ('Dans la peau de sphincter cell',               'dans-la-peau-de-sphincter-cell',              'https://www.dofuspourlesnoobs.com/dans-la-peau-de-sphincter-cell.html'),
  ('Le forgeron aux deux mains gauches',           'le-forgeron-aux-deux-mains-gauches',          'https://www.dofuspourlesnoobs.com/le-forgeron-aux-deux-mains-gauches.html'),
  ('Mon nom est poison',                           'mon-nom-est-poison',                          'https://www.dofuspourlesnoobs.com/mon-nom-est-poison.html'),
  ('Un maitre es pion',                            'un-maitre-es-pion',                           'https://www.dofuspourlesnoobs.com/un-maitre-es-pion.html'),
  ('Le magnanime',                                 'le-magnanime',                                'https://www.dofuspourlesnoobs.com/le-magnanime.html'),
  ('Supermilicien',                                'supermilicien',                               'https://www.dofuspourlesnoobs.com/supermilicien.html'),
  ('Le forgeron',                                  'le-forgeron',                                 'https://www.dofuspourlesnoobs.com/le-forgeron.html'),
  ('Paranoia aigue',                               'paranoia-aigue',                              'https://www.dofuspourlesnoobs.com/paranoia-aigue.html'),
  ('A la maniere des Brakmariens',                 'a-la-maniere-des-brakmariens',                'https://www.dofuspourlesnoobs.com/a-la-maniere-des-brakmariens.html'),
  ('Le tresor de La descemer',                     'le-tresor-de-la-descemer',                    'https://www.dofuspourlesnoobs.com/le-tresor-de-la-descemer.html'),
  ('Une rumeur allechante',                        'une-rumeur-allechante',                       'https://www.dofuspourlesnoobs.com/une-rumeur-allechante.html'),
  ('Enquete a moon',                               'enquete-a-moon',                              'https://www.dofuspourlesnoobs.com/enquete-a-moon.html'),
  ('Maniere forte',                                'maniere-forte',                               'https://www.dofuspourlesnoobs.com/maniere-forte.html'),
  ('Retour aux origines',                          'retour-aux-origines',                         'https://www.dofuspourlesnoobs.com/retour-aux-origines.html'),
  ('Une faille dans sa carapace',                  'une-faille-dans-sa-carapace',                 'https://www.dofuspourlesnoobs.com/une-faille-dans-sa-carapace.html'),
  ('Les documents avant tout',                     'les-documents-avant-tout',                    'https://www.dofuspourlesnoobs.com/les-documents-avant-tout.html'),
  ('Les ordres sont-ils les ordres',               'les-ordres-sont-ils-les-ordres',              'https://www.dofuspourlesnoobs.com/les-ordres-sont-ils-les-ordres.html'),
  ('Contre-espion',                                'contre-espion',                               'https://www.dofuspourlesnoobs.com/contre-espion.html'),
  ('Histoires de salaces',                         'histoires-de-salaces',                        'https://www.dofuspourlesnoobs.com/histoires-de-salaces.html'),
  ('Affrontement',                                 'affrontement',                                'https://www.dofuspourlesnoobs.com/affrontement.html'),
  ('Legitime defense',                             'legitime-defense',                            'https://www.dofuspourlesnoobs.com/legitime-defense.html'),
  ('L''epee maudite',                              'l-epee-maudite',                              'https://www.dofuspourlesnoobs.com/l-epee-maudite.html'),
  ('Allez, ce fer',                                'allez-ce-fer',                                'https://www.dofuspourlesnoobs.com/allez-ce-fer.html'),
  ('Poignee d''amour',                             'poignee-d-amour',                             'https://www.dofuspourlesnoobs.com/poignee-d-amour.html'),
  ('Le marteau des chus',                          'le-marteau-des-chus',                         'https://www.dofuspourlesnoobs.com/le-marteau-des-chus.html'),
  ('L''epee, ca sent mauvais',                     'l-epee-ca-sent-mauvais',                      'https://www.dofuspourlesnoobs.com/l-epee-ca-sent-mauvais.html'),
  ('Plus, plus de puissance',                      'plus-plus-de-puissance',                      'https://www.dofuspourlesnoobs.com/plus-plus-de-puissance.html'),
  ('Des recherches sur la corne',                  'des-recherches-sur-la-corne',                 'https://www.dofuspourlesnoobs.com/des-recherches-sur-la-corne.html'),
  ('Maitre chanteur',                              'maitre-chanteur',                             'https://www.dofuspourlesnoobs.com/maitre-chanteur.html'),
  ('Comploteur malgre lui',                        'comploteur-malgre-lui',                       'https://www.dofuspourlesnoobs.com/comploteur-malgre-lui.html'),
  ('Le roi estitsh',                               'le-roi-estitsh',                              'https://www.dofuspourlesnoobs.com/le-roi-estitsh.html'),
  ('Le trou d''uk',                                'le-trou-d-uk',                                'https://www.dofuspourlesnoobs.com/le-trou-d-uk.html'),
  ('Gaspiller l''energie ensemble',                'gaspiller-l-energie-ensemble',                'https://www.dofuspourlesnoobs.com/gaspiller-l-energie-ensemble.html'),
  ('Gemme les joyaux',                             'gemme-les-joyaux',                            'https://www.dofuspourlesnoobs.com/gemme-les-joyaux.html'),
  ('L''arakne de leng',                            'l-arakne-de-leng',                            'https://www.dofuspourlesnoobs.com/l-arakne-de-leng.html'),
  ('Marque d''une pierre blanche',                 'marque-d-une-pierre-blanche',                 'https://www.dofuspourlesnoobs.com/marque-d-une-pierre-blanche.html'),
  ('L''essor de qu''tan',                          'l-essor-de-qu-tan',                           'https://www.dofuspourlesnoobs.com/l-essor-de-qu-tan.html'),
  ('L''habit ne fait pas le moine',                'l-habit-ne-fait-pas-le-moine',                'https://www.dofuspourlesnoobs.com/l-habit-ne-fait-pas-le-moine.html'),
  ('Les clefs du malheur',                         'les-clefs-du-malheur',                        'https://www.dofuspourlesnoobs.com/les-clefs-du-malheur.html'),
  ('Chaud devant',                                 'chaud-devant',                                'https://www.dofuspourlesnoobs.com/chaud-devant.html'),
  ('La vengeance est un plat qui se mange froid',  'la-vengeance-est-un-plat-qui-se-mange-froid', 'https://www.dofuspourlesnoobs.com/la-vengeance-est-un-plat-qui-se-mange-froid.html'),
  ('Melodie en sous-sol',                          'melodie-en-sous-sol',                         'https://www.dofuspourlesnoobs.com/melodie-en-sous-sol.html'),
  ('Un monde en pets',                             'un-monde-en-pets',                            'https://www.dofuspourlesnoobs.com/un-monde-en-pets.html'),
  ('Mieux vaut guerir que mourir',                 'mieux-vaut-guerir-que-mourir',                'https://www.dofuspourlesnoobs.com/mieux-vaut-guerir-que-mourir.html'),
  ('Le crepuscule des morts-vivants',              'le-crepuscule-des-morts-vivants',             'https://www.dofuspourlesnoobs.com/le-crepuscule-des-morts-vivants.html'),
  ('Le faux cul',                                  'le-faux-cul',                                 'https://www.dofuspourlesnoobs.com/le-faux-cul.html'),
  ('Cryptomane',                                   'cryptomane',                                  'https://www.dofuspourlesnoobs.com/cryptomane.html'),
  ('Sueurs froides',                               'sueurs-froides',                              'https://www.dofuspourlesnoobs.com/sueurs-froides.html'),
  ('Sur la route d''erazal',                       'sur-la-route-d-erazal',                       'https://www.dofuspourlesnoobs.com/sur-la-route-d-erazal.html'),
  ('Lettre à ilyz',                                'lettre-a-ilyz',                               'https://www.dofuspourlesnoobs.com/lettre-a-ilyz.html'),
  ('La danse macabre',                             'la-danse-macabre',                            'https://www.dofuspourlesnoobs.com/la-danse-macabre.html'),
  -- Ordres Bonta manquants
  ('Apprentissage : Disciple de menalt',           'apprentissage-disciple-de-menalt',            'https://www.dofuspourlesnoobs.com/apprentissage-disciple-de-menalt.html'),
  ('Apprentissage : Ecuyer',                       'apprentissage-ecuyer',                        'https://www.dofuspourlesnoobs.com/apprentissage-ecuyer.html'),
  ('Apprentissage : Chevalier de l''espoir',       'apprentissage-chevalier-de-l-espoir',         'https://www.dofuspourlesnoobs.com/apprentissage-chevalier-de-l-espoir.html'),
  ('Apprentissage : Champion merveilleux',         'apprentissage-champion-merveilleux',          'https://www.dofuspourlesnoobs.com/apprentissage-champion-merveilleux.html'),
  ('Apprentissage : Heros legendaire',             'apprentissage-heros-legendaire',              'https://www.dofuspourlesnoobs.com/apprentissage-heros-legendaire.html'),
  ('Apprentissage : Disciple de jiva',             'apprentissage-disciple-de-jiva',              'https://www.dofuspourlesnoobs.com/apprentissage-disciple-de-jiva.html'),
  ('Apprentissage : Apprenti eclaire',             'apprentissage-apprenti-eclaire',              'https://www.dofuspourlesnoobs.com/apprentissage-apprenti-eclaire.html'),
  ('Apprentissage : Adepte des ecrits',            'apprentissage-adepte-des-ecrits',             'https://www.dofuspourlesnoobs.com/apprentissage-adepte-des-ecrits.html'),
  ('Apprentissage : Maitre des parchemins',        'apprentissage-maitre-des-parchemins',         'https://www.dofuspourlesnoobs.com/apprentissage-maitre-des-parchemins.html'),
  ('Apprentissage : Gardien du savoir',            'apprentissage-gardien-du-savoir',             'https://www.dofuspourlesnoobs.com/apprentissage-gardien-du-savoir.html'),
  -- Ordres Brakmar
  ('Apprentissage : Disciple de djaul',            'apprentissage-disciple-de-djaul',             'https://www.dofuspourlesnoobs.com/apprentissage-disciple-de-djaul.html'),
  ('Apprentissage : Surineur',                     'apprentissage-surineur',                      'https://www.dofuspourlesnoobs.com/apprentissage-surineur.html'),
  ('Apprentissage : Chevalier du desespoir',       'apprentissage-chevalier-du-desespoir',        'https://www.dofuspourlesnoobs.com/apprentissage-chevalier-du-desespoir.html'),
  ('Apprentissage : Champion du chaos',            'apprentissage-champion-du-chaos',             'https://www.dofuspourlesnoobs.com/apprentissage-champion-du-chaos.html'),
  ('Apprentissage : Heros de l''apocalypse',       'apprentissage-heros-de-l-apocalypse',         'https://www.dofuspourlesnoobs.com/apprentissage-heros-de-l-apocalypse.html'),
  ('Apprentissage : Disciple de brumaire',         'apprentissage-disciple-de-brumaire',          'https://www.dofuspourlesnoobs.com/apprentissage-disciple-de-brumaire.html'),
  ('Apprentissage : Espion sombre',                'apprentissage-espion-sombre',                 'https://www.dofuspourlesnoobs.com/apprentissage-espion-sombre.html'),
  ('Apprentissage : Chasseur d''ames',             'apprentissage-chasseur-d-ames',               'https://www.dofuspourlesnoobs.com/apprentissage-chasseur-d-ames.html'),
  ('Apprentissage : Psychopathe',                  'apprentissage-psychopathe',                   'https://www.dofuspourlesnoobs.com/apprentissage-psychopathe.html'),
  ('Apprentissage : Maitre des ombres',            'apprentissage-maitre-des-ombres',             'https://www.dofuspourlesnoobs.com/apprentissage-maitre-des-ombres.html'),
  ('Apprentissage : Disciple d''hecate',           'apprentissage-disciple-d-hecate',             'https://www.dofuspourlesnoobs.com/apprentissage-disciple-d-hecate.html'),
  ('Apprentissage : Apprenti sombre',              'apprentissage-apprenti-sombre',               'https://www.dofuspourlesnoobs.com/apprentissage-apprenti-sombre.html'),
  ('Apprentissage : Adepte des Douleurs',          'apprentissage-adepte-des-douleurs',           'https://www.dofuspourlesnoobs.com/apprentissage-adepte-des-douleurs.html'),
  ('Apprentissage : Maitre des sevices',           'apprentissage-maitre-des-sevices',            'https://www.dofuspourlesnoobs.com/apprentissage-maitre-des-sevices.html'),
  ('Apprentissage : Gardien des tortures',         'apprentissage-gardien-des-tortures',          'https://www.dofuspourlesnoobs.com/apprentissage-gardien-des-tortures.html')
ON CONFLICT (slug) DO NOTHING;


-- ----------------------------------------------------------------
-- 2. Insérer les chains manquantes pour dofus-ivoire
-- ----------------------------------------------------------------
INSERT INTO dofus_quest_chains
  (dofus_id, quest_id, section, sub_section, order_index, alignment, alignment_order, group_id, quest_types, combat_count, is_avoidable)
SELECT
  (SELECT id FROM dofus WHERE slug = 'dofus-ivoire'),
  q.id,
  src.section,
  src.sub_section,
  src.order_index,
  src.alignment,
  src.alignment_order,
  NULL,
  '{}',
  NULL,
  false
FROM (VALUES
  -- ── Brakmar 1-102 (sub_section Partie 1, brakmarien) ──────────────────
  ('cliquetis-fou',                               'main', 'Prérequis - Partie 1', 400, 'brakmarien', NULL),
  ('le-professionnel',                            'main', 'Prérequis - Partie 1', 401, 'brakmarien', NULL),
  ('un-coup-de-fouet',                            'main', 'Prérequis - Partie 1', 402, 'brakmarien', NULL),
  ('le-dentiste-dement',                          'main', 'Prérequis - Partie 1', 403, 'brakmarien', NULL),
  ('la-revanche-de-mak',                          'main', 'Prérequis - Partie 1', 404, 'brakmarien', NULL),
  ('la-noirceur-des-armes-blanches',              'main', 'Prérequis - Partie 1', 405, 'brakmarien', NULL),
  ('la-mise-a-mort',                              'main', 'Prérequis - Partie 1', 406, 'brakmarien', NULL),
  ('les-gardes-d-honneur-a-punir',                'main', 'Prérequis - Partie 1', 407, 'brakmarien', NULL),
  ('un-oubli-regrettable',                        'main', 'Prérequis - Partie 1', 408, 'brakmarien', NULL),
  ('tete-de-gland',                               'main', 'Prérequis - Partie 1', 409, 'brakmarien', NULL),
  ('pauvre-larve',                                'main', 'Prérequis - Partie 1', 410, 'brakmarien', NULL),
  ('pauvre-larve-doree',                          'main', 'Prérequis - Partie 1', 411, 'brakmarien', NULL),
  ('agent-double-et-demi',                        'main', 'Prérequis - Partie 1', 412, 'brakmarien', NULL),
  ('livreur-de-mauvaise-nouvelle',                'main', 'Prérequis - Partie 1', 413, 'brakmarien', NULL),
  ('une-collection-digne-de-xilebo',              'main', 'Prérequis - Partie 1', 414, 'brakmarien', NULL),
  ('d-egout-pille',                               'main', 'Prérequis - Partie 1', 415, 'brakmarien', NULL),
  ('le-tabi-mangeur-de-blops',                    'main', 'Prérequis - Partie 1', 416, 'brakmarien', NULL),
  ('alchimie-malfaisante',                        'main', 'Prérequis - Partie 1', 417, 'brakmarien', NULL),
  ('des-capes-typiques',                          'main', 'Prérequis - Partie 1', 418, 'brakmarien', NULL),
  ('le-testament-du-papa',                        'main', 'Prérequis - Partie 1', 419, 'brakmarien', NULL),
  ('amadouer-ou-corrompre',                       'main', 'Prérequis - Partie 1', 420, 'brakmarien', NULL),
  ('taxe-gratuite',                               'main', 'Prérequis - Partie 1', 421, 'brakmarien', NULL),
  ('par-la-force-ou-par-la-finesse',              'main', 'Prérequis - Partie 1', 422, 'brakmarien', NULL),
  ('le-dur-travail-d-eplucheur-de-patates',       'main', 'Prérequis - Partie 1', 423, 'brakmarien', NULL),
  ('cruel-mais-a-quel-point',                     'main', 'Prérequis - Partie 1', 424, 'brakmarien', NULL),
  ('activites-volcaniques',                       'main', 'Prérequis - Partie 1', 425, 'brakmarien', NULL),
  ('chasse-a-l-espion',                           'main', 'Prérequis - Partie 1', 426, 'brakmarien', NULL),
  ('un-petit-oubli',                              'main', 'Prérequis - Partie 1', 427, 'brakmarien', NULL),
  ('du-venin-sinon-rien',                         'main', 'Prérequis - Partie 1', 428, 'brakmarien', NULL),
  ('le-defi-du-maitre-guerrier',                  'main', 'Prérequis - Partie 1', 429, 'brakmarien', NULL),
  ('joie-de-courte-duree',                        'main', 'Prérequis - Partie 1', 430, 'brakmarien', NULL),
  ('au-combat',                                   'main', 'Prérequis - Partie 1', 431, 'brakmarien', NULL),
  ('un-assassin-a-bonta',                         'main', 'Prérequis - Partie 1', 432, 'brakmarien', NULL),
  ('un-dentier-pour-l-ami-mak',                   'main', 'Prérequis - Partie 1', 433, 'brakmarien', NULL),
  ('un-choix-difficile',                          'main', 'Prérequis - Partie 1', 434, 'brakmarien', NULL),
  ('arrivee-a-bon-port',                          'main', 'Prérequis - Partie 1', 435, 'brakmarien', NULL),
  ('humiliation-sans-precedent',                  'main', 'Prérequis - Partie 1', 436, 'brakmarien', NULL),
  ('opposition-aux-opposants',                    'main', 'Prérequis - Partie 1', 437, 'brakmarien', NULL),
  ('a-la-rescousse-d-un-incapable',               'main', 'Prérequis - Partie 1', 438, 'brakmarien', NULL),
  ('mulanthropie',                                'main', 'Prérequis - Partie 1', 439, 'brakmarien', NULL),
  ('triple-x',                                    'main', 'Prérequis - Partie 1', 440, 'brakmarien', NULL),
  ('x-comme-xephires',                            'main', 'Prérequis - Partie 1', 441, 'brakmarien', NULL),
  ('operation-commando',                          'main', 'Prérequis - Partie 1', 442, 'brakmarien', NULL),
  ('rencontre-du-premier-type',                   'main', 'Prérequis - Partie 1', 443, 'brakmarien', NULL),
  ('joyau-ze-fete',                               'main', 'Prérequis - Partie 1', 444, 'brakmarien', NULL),
  ('le-cristal-de-kain-dharyn',                   'main', 'Prérequis - Partie 1', 445, 'brakmarien', NULL),
  ('cambriolage',                                 'main', 'Prérequis - Partie 1', 446, 'brakmarien', NULL),
  ('livraison-rapide',                            'main', 'Prérequis - Partie 1', 447, 'brakmarien', NULL),
  ('le-moment-de-verite',                         'main', 'Prérequis - Partie 1', 448, 'brakmarien', NULL),
  ('le-puits-sans-fond',                          'main', 'Prérequis - Partie 1', 449, 'brakmarien', NULL),
  ('le-carnage-des-plaines',                      'main', 'Prérequis - Partie 1', 450, 'brakmarien', NULL),
  ('dans-la-peau-de-sphincter-cell',              'main', 'Prérequis - Partie 1', 451, 'brakmarien', NULL),
  ('le-forgeron-aux-deux-mains-gauches',          'main', 'Prérequis - Partie 1', 452, 'brakmarien', NULL),
  ('mon-nom-est-poison',                          'main', 'Prérequis - Partie 1', 453, 'brakmarien', NULL),
  ('un-maitre-es-pion',                           'main', 'Prérequis - Partie 1', 454, 'brakmarien', NULL),
  ('le-magnanime',                                'main', 'Prérequis - Partie 1', 455, 'brakmarien', NULL),
  ('supermilicien',                               'main', 'Prérequis - Partie 1', 456, 'brakmarien', NULL),
  ('le-forgeron',                                 'main', 'Prérequis - Partie 1', 457, 'brakmarien', NULL),
  ('paranoia-aigue',                              'main', 'Prérequis - Partie 1', 458, 'brakmarien', NULL),
  ('a-la-maniere-des-brakmariens',                'main', 'Prérequis - Partie 1', 459, 'brakmarien', NULL),
  ('le-tresor-de-la-descemer',                    'main', 'Prérequis - Partie 1', 460, 'brakmarien', NULL),
  ('une-rumeur-allechante',                       'main', 'Prérequis - Partie 1', 461, 'brakmarien', NULL),
  ('enquete-a-moon',                              'main', 'Prérequis - Partie 1', 462, 'brakmarien', NULL),
  ('maniere-forte',                               'main', 'Prérequis - Partie 1', 463, 'brakmarien', NULL),
  ('retour-aux-origines',                         'main', 'Prérequis - Partie 1', 464, 'brakmarien', NULL),
  ('une-faille-dans-sa-carapace',                 'main', 'Prérequis - Partie 1', 465, 'brakmarien', NULL),
  ('les-documents-avant-tout',                    'main', 'Prérequis - Partie 1', 466, 'brakmarien', NULL),
  ('les-ordres-sont-ils-les-ordres',              'main', 'Prérequis - Partie 1', 467, 'brakmarien', NULL),
  ('contre-espion',                               'main', 'Prérequis - Partie 1', 468, 'brakmarien', NULL),
  ('histoires-de-salaces',                        'main', 'Prérequis - Partie 1', 469, 'brakmarien', NULL),
  ('affrontement',                                'main', 'Prérequis - Partie 1', 470, 'brakmarien', NULL),
  ('legitime-defense',                            'main', 'Prérequis - Partie 1', 471, 'brakmarien', NULL),
  ('l-epee-maudite',                              'main', 'Prérequis - Partie 1', 472, 'brakmarien', NULL),
  ('allez-ce-fer',                                'main', 'Prérequis - Partie 1', 473, 'brakmarien', NULL),
  ('poignee-d-amour',                             'main', 'Prérequis - Partie 1', 474, 'brakmarien', NULL),
  ('le-marteau-des-chus',                         'main', 'Prérequis - Partie 1', 475, 'brakmarien', NULL),
  ('l-epee-ca-sent-mauvais',                      'main', 'Prérequis - Partie 1', 476, 'brakmarien', NULL),
  ('plus-plus-de-puissance',                      'main', 'Prérequis - Partie 1', 477, 'brakmarien', NULL),
  ('des-recherches-sur-la-corne',                 'main', 'Prérequis - Partie 1', 478, 'brakmarien', NULL),
  ('maitre-chanteur',                             'main', 'Prérequis - Partie 1', 479, 'brakmarien', NULL),
  ('comploteur-malgre-lui',                       'main', 'Prérequis - Partie 1', 480, 'brakmarien', NULL),
  ('le-roi-estitsh',                              'main', 'Prérequis - Partie 1', 481, 'brakmarien', NULL),
  ('le-trou-d-uk',                                'main', 'Prérequis - Partie 1', 482, 'brakmarien', NULL),
  ('gaspiller-l-energie-ensemble',                'main', 'Prérequis - Partie 1', 483, 'brakmarien', NULL),
  ('gemme-les-joyaux',                            'main', 'Prérequis - Partie 1', 484, 'brakmarien', NULL),
  ('l-arakne-de-leng',                            'main', 'Prérequis - Partie 1', 485, 'brakmarien', NULL),
  ('marque-d-une-pierre-blanche',                 'main', 'Prérequis - Partie 1', 486, 'brakmarien', NULL),
  ('l-essor-de-qu-tan',                           'main', 'Prérequis - Partie 1', 487, 'brakmarien', NULL),
  ('l-habit-ne-fait-pas-le-moine',                'main', 'Prérequis - Partie 1', 488, 'brakmarien', NULL),
  ('les-clefs-du-malheur',                        'main', 'Prérequis - Partie 1', 489, 'brakmarien', NULL),
  ('chaud-devant',                                'main', 'Prérequis - Partie 1', 490, 'brakmarien', NULL),
  ('la-vengeance-est-un-plat-qui-se-mange-froid', 'main', 'Prérequis - Partie 1', 491, 'brakmarien', NULL),
  ('melodie-en-sous-sol',                         'main', 'Prérequis - Partie 1', 492, 'brakmarien', NULL),
  ('un-monde-en-pets',                            'main', 'Prérequis - Partie 1', 493, 'brakmarien', NULL),
  ('mieux-vaut-guerir-que-mourir',                'main', 'Prérequis - Partie 1', 494, 'brakmarien', NULL),
  ('le-crepuscule-des-morts-vivants',             'main', 'Prérequis - Partie 1', 495, 'brakmarien', NULL),
  ('le-faux-cul',                                 'main', 'Prérequis - Partie 1', 496, 'brakmarien', NULL),
  ('cryptomane',                                  'main', 'Prérequis - Partie 1', 497, 'brakmarien', NULL),
  ('sueurs-froides',                              'main', 'Prérequis - Partie 1', 498, 'brakmarien', NULL),
  ('sur-la-route-d-erazal',                       'main', 'Prérequis - Partie 1', 499, 'brakmarien', NULL),
  ('lettre-a-ilyz',                               'main', 'Prérequis - Partie 1', 500, 'brakmarien', NULL),
  ('la-danse-macabre',                            'main', 'Prérequis - Partie 1', 501, 'brakmarien', NULL),
  -- ── Ordres Bonta manquants ────────────────────────────────────────────
  ('apprentissage-disciple-de-menalt',            'main', 'Prérequis - Partie 1', 300, 'bontarien', 'coeur-vaillant'),
  ('apprentissage-ecuyer',                        'main', 'Prérequis - Partie 1', 301, 'bontarien', 'coeur-vaillant'),
  ('apprentissage-chevalier-de-l-espoir',         'main', 'Prérequis - Partie 1', 302, 'bontarien', 'coeur-vaillant'),
  ('apprentissage-champion-merveilleux',          'main', 'Prérequis - Partie 1', 303, 'bontarien', 'coeur-vaillant'),
  ('apprentissage-heros-legendaire',              'main', 'Prérequis - Partie 1', 304, 'bontarien', 'coeur-vaillant'),
  ('apprentissage-disciple-de-jiva',              'main', 'Prérequis - Partie 1', 305, 'bontarien', 'esprit-salvateur'),
  ('apprentissage-apprenti-eclaire',              'main', 'Prérequis - Partie 1', 306, 'bontarien', 'esprit-salvateur'),
  ('apprentissage-adepte-des-ecrits',             'main', 'Prérequis - Partie 1', 307, 'bontarien', 'esprit-salvateur'),
  ('apprentissage-maitre-des-parchemins',         'main', 'Prérequis - Partie 1', 308, 'bontarien', 'esprit-salvateur'),
  ('apprentissage-gardien-du-savoir',             'main', 'Prérequis - Partie 1', 309, 'bontarien', 'esprit-salvateur'),
  -- ── Ordres Brakmar ────────────────────────────────────────────────────
  ('apprentissage-disciple-de-djaul',             'main', 'Prérequis - Partie 1', 502, 'brakmarien', 'coeur-saignant'),
  ('apprentissage-surineur',                      'main', 'Prérequis - Partie 1', 503, 'brakmarien', 'coeur-saignant'),
  ('apprentissage-chevalier-du-desespoir',        'main', 'Prérequis - Partie 1', 504, 'brakmarien', 'coeur-saignant'),
  ('apprentissage-champion-du-chaos',             'main', 'Prérequis - Partie 1', 505, 'brakmarien', 'coeur-saignant'),
  ('apprentissage-heros-de-l-apocalypse',         'main', 'Prérequis - Partie 1', 506, 'brakmarien', 'coeur-saignant'),
  ('apprentissage-disciple-de-brumaire',          'main', 'Prérequis - Partie 1', 507, 'brakmarien', 'oeil-putride'),
  ('apprentissage-espion-sombre',                 'main', 'Prérequis - Partie 1', 508, 'brakmarien', 'oeil-putride'),
  ('apprentissage-chasseur-d-ames',               'main', 'Prérequis - Partie 1', 509, 'brakmarien', 'oeil-putride'),
  ('apprentissage-psychopathe',                   'main', 'Prérequis - Partie 1', 510, 'brakmarien', 'oeil-putride'),
  ('apprentissage-maitre-des-ombres',             'main', 'Prérequis - Partie 1', 511, 'brakmarien', 'oeil-putride'),
  ('apprentissage-disciple-d-hecate',             'main', 'Prérequis - Partie 1', 512, 'brakmarien', 'esprit-malsain'),
  ('apprentissage-apprenti-sombre',               'main', 'Prérequis - Partie 1', 513, 'brakmarien', 'esprit-malsain'),
  ('apprentissage-adepte-des-douleurs',           'main', 'Prérequis - Partie 1', 514, 'brakmarien', 'esprit-malsain'),
  ('apprentissage-maitre-des-sevices',            'main', 'Prérequis - Partie 1', 515, 'brakmarien', 'esprit-malsain'),
  ('apprentissage-gardien-des-tortures',          'main', 'Prérequis - Partie 1', 516, 'brakmarien', 'esprit-malsain')
) AS src(slug, section, sub_section, order_index, alignment, alignment_order)
JOIN quests q ON q.slug = src.slug
ON CONFLICT (dofus_id, quest_id) DO UPDATE SET
  alignment       = EXCLUDED.alignment,
  alignment_order = EXCLUDED.alignment_order,
  sub_section     = EXCLUDED.sub_section;


-- ----------------------------------------------------------------
-- 3. Vérification
-- ----------------------------------------------------------------
SELECT alignment, alignment_order, COUNT(*) AS nb
FROM dofus_quest_chains
WHERE dofus_id = (SELECT id FROM dofus WHERE slug = 'dofus-ivoire')
  AND sub_section = 'Prérequis - Partie 1'
GROUP BY alignment, alignment_order
ORDER BY alignment, alignment_order;
